site_name: HEXROLL Guidebook
extra_css:
  - /stylesheets/extra.css
nav:
  - Getting Started:
      - What is Hexroll?: getting-started/index.md
      - Rolling a Sandbox: getting-started/new-sandbox.md
      - The Hex Map: getting-started/the-hex-map.md
      - Crawl Mode: getting-started/crawl-mode.md
      - Search Box: getting-started/searching.md
      - Quick Help: getting-started/help.md
      - FAQ: getting-started/faq.md
  - Building a Sandbox:
      - Generating a Realm: building-a-sandbox/generating-a-realm.md
      - Editing the Map: building-a-sandbox/map-editing.md
      - Rerolling Content: building-a-sandbox/rerolling-content.md
      - Editing Content: building-a-sandbox/editing-content.md
      - Ephemeral Sandboxes: building-a-sandbox/ephemeral.md
  - Playing with Hexroll:
      - It's Just a Tool: playing-with-hexroll/its-just-a-tool.md
      - Solo and No-Spoilers: playing-with-hexroll/solo.md
      - Dice Box: playing-with-hexroll/dice.md
      - Map Pins: playing-with-hexroll/pins.md
      - VTT Projection: playing-with-hexroll/vtt-projection.md
      - Using Hexroll Offline: playing-with-hexroll/using-hexroll-offline.md
  - Modding using SCROLL:
      - Scroll Tutorial: scroll/scroll-tutorial.md
      - Modding Guide: scroll/scroll-mods.md
      - Scrolls Archive: scroll/scrolls-archive.md
      - Sandbox Graph Behaviors: hexroll-internals/graph-behavior.md
theme:
  logo: images/logo.png
  font:
    text: Poppins
  name: material
  features:
    - header.autohide
    - navigation.tabs
    - navigation.footer
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
